# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: LaTeX Math for Obsidian
site_url: https://github.com/zarstensen/obsidian-latex-math
repo_url: https://github.com/zarstensen/obsidian-latex-math
theme:
  name: material
  font:
    code: JetBrains Mono
  palette:
    primary: grey
    accent: deep purple
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.keys
  - admonition
plugins:
  - search
  - callouts
  - offline
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
