# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: LaTeX Math for Obsidian
site_url: https://github.com/zarstensen/obsidian-latex-math
theme:
  name: material
  font:
    code: JetBrains Mono
  palette:
    primary: grey
    accent: deep purple
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
