target-version = "py312"

[lint]

extend-select = [
    # imports
    "I",
    "F401",
    # single newline at end of file
    "W292",
    "W391",
    # unneeded whitespace
    "W291",
    "W293",
]

extend-ignore = ["F405", "F403"]

extend-safe-fixes = ["W291"]
