%import .cas_expr.substitute_symbol -> cas_expr__substitute_symbol
// ======== Propositional Logic Structure ========

// represents a chain of propositions, separated by equivalence symbols
cas_logic_expression: _proposition (_EQUIV _proposition)*

// represents a single proposition in a series of chained propositions
_proposition: _bool_value | _delimited_proposition | not | xnor | xor | nor | and | nand | or | implies | iff
// represents a single proposition surrounded by parenthesess, brackets or braces.
_delimited_proposition: _L_PAREN _proposition _R_PAREN | _L_BRACKET _proposition _R_BRACKET | _L_BRACE _proposition _R_BRACE

// propositional operator presedence is based on wolfram alpha: https://www.wolframalpha.com/input?i=not+A+xor+B+nor++C+and+D+nand+E+or+F+implies+G+%3C%3D%3E+H

iff: iff_arg (_BIIMPLICATION iff_arg)+
?iff_arg: implies_arg | implies

!implies: implies_arg ((_LR_IMPLICATION|_NEG_LR_IMPLICATION|_RL_IMPLICATION|_NEG_RL_IMPLICATION) implies_arg)+
?implies_arg: or_arg | or

or: or_arg (_OR or_arg)+
?or_arg: nand_arg | nand

nand: nand_arg (_NAND nand_arg)+
?nand_arg: and_arg | and

and: and_arg (_AND and_arg)+
?and_arg: nor_arg | nor

nor: nor_arg (_NOR nor_arg)+
?nor_arg: xor_arg | xor

xor: xor_arg (_XOR xor_arg)+
?xor_arg: xnor_arg | xnor

xnor: xnor_arg (_XNOR xnor_arg)+
?xnor_arg: not_arg | not

not: _NOT not_arg
?not_arg: _delimited_proposition | cas_expr__substitute_symbol | _bool_value
_bool_value: CMD_TAUTOLOGY | CMD_CONTRADICTION

// ======== propositional logic ========

CMD_TAUTOLOGY.1: /\\(?:mathrm|operatorname)\s*{\s*(?:T|True|TRUE)\s*}/ | "T" | "\\top"
CMD_CONTRADICTION.1: /\\(?:mathrm|operatorname)\s*{\s*(?:F|False|FALSE)\s*}/ | "F" | "\\bot"

_CMD_DOT: "\\dot"

_BIIMPLICATION: "\\iff"
    | /\\(?:[Ll]ongl|[Ll])eftrightarrow/
    | /\\(?:leftright|rightleft)harpoons/
_LR_IMPLICATION: "\\implies"
    | "\\to"
    | /\\(?:[Ll]ongr|[Rr])ightarrow/
_NEG_LR_IMPLICATION: /\\n[Rr]ightarrow/
_RL_IMPLICATION: /\\(?:[Ll]ongl|[Ll])eftarrow/
_NEG_RL_IMPLICATION: /\\n[Ll]eftarrow/
_OR: /\\(big)?vee/
    | "\\lor"
_NAND: (_CMD_BAR|_CMD_OVERLINE) _WS? (_AND | _L_BRACE _WS? _AND _WS? _R_BRACE)
_AND: /\\(big)?wedge/
    | "\\land"
_NOR: (_CMD_BAR|_CMD_OVERLINE) _WS? (_OR | _L_BRACE _WS? _OR _WS? _R_BRACE)
_XOR: /\\(big)?oplus/
    | "\\veebar"
    | _CMD_DOT _WS? (_OR | _L_BRACE _WS? _OR _WS? _R_BRACE)
_XNOR: "\\odot"
    | (_CMD_BAR|_CMD_OVERLINE) _WS? ( _XOR | _L_BRACE _WS? (_XOR) _WS? _R_BRACE)
_NOT: "\\neg"
    | "\\sim"
_PREFIX_NOT: "\\not"

_EQUIV: "\\equiv"
