// Terminals are loosley based on sympy's original latex.lark: https://github.com/sympy/sympy/blob/2e7baea39cd0d891433bdc2ef2222e445c381ca3/sympy/parsing/latex/lark/grammar/latex.lark
// grammar has been written from the ground up to support the faster lalr parser instead of earley.

// ======== Core structure ========


// a cas expression, is a system of Basic sympy objects + some additional parsing metadata
cas_expression: _system_of_relations

_rel_op: EQUAL | NOT_EQUAL | LT | LTE | GT | GTE
_align: _ALIGN | _LATEX_NEWLINE
relation: (_align* _rel_op)? expression (_rel_op expression)* (_rel_op _align*)?

// an expression is a sum of terms
expression: (_align* (ADD|SUB))? term ((ADD|SUB) term)*

// a term is a series of products of factors separated by product operators.
term: implicit_multiplication ((OPERATOR_MUL|OPERATOR_CROSS|OPERATOR_DIV) (_align* (ADD|SUB))? implicit_multiplication)*

// factors with no operator between them are implicitly multiplied together.
implicit_multiplication: _align* factor (_align* factor)* _align*

// a factor is either a number, a constant, a symbol, or a function.
// here exponentiation, fractions, binomials are loosly seen as functions.
?factor: exponentiation_ext
    | factor_func_arg
    | unit
    | function_noarg

// matches all factors which may be passed to a mathematical function (excluding postfix functions) as an argument
?factor_func_arg: factor_func_postfix_arg
    | _delimitedfactor

// matches all factors which may be passed to a post fix mathematical function (factorial, percent, ...) WHICH may be passed to another mathematical function as an argument.
// e.g. \sin x! this rule should match x, since x is an allowed arg in x! and x! is an allowed arg to \sin x!.
// should not match (x) in e.g. \sin(x)! since (x)! is not passable as an arg to \sin.
// this should instead be interpreted as (\sin(x))!, which another rule will take care of.
?factor_func_postfix_arg: exponentiation_arg
    | basefactor_arg

// matches all base factors in an exponentiation, which may be passed to a mathematical function as an argument.
?basefactor_arg: substitute_symbol
    | function_as_arg
    | _number
    | _matrix_notation

// various rules for grouping expressions surrounded by delimiters.
_delimitedfactor: parenthesees_expression | brackets_expression | braces_expression

?parenthesees_expression: _L_PAREN expression _R_PAREN
?braces_expression: _L_BRACE expression _R_BRACE
?brackets_expression: _L_BRACKET expression _R_BRACKET

// groups a base factor and an exponent factor to be evaluated in an exponentation.
// this variant matches only exponentiations which may be used as arguments to functions.
// e.g. it should match x^2 in \sin x^2 but not (x + y)^2 in \sin(x+ y)^2
//
// exponentiation_arg combined with exponentiation_ext should match all exponentiations possible. 
exponentiation_arg: basefactor_arg _CARET function_special_arg -> exponentiation
    | basefactor_arg _CARET (ADJOINT_TRANSPOSE_EXPONENT|ADJOINT_TRANSPOSE_EXPONENTS) -> exp_transpose

?exponentiation_ext: (unit|_delimitedfactor|function_noarg) _CARET function_special_arg -> exponentiation
    | (unit|_delimitedfactor|function_noarg) _CARET (ADJOINT_TRANSPOSE_EXPONENT|ADJOINT_TRANSPOSE_EXPONENTS) -> exp_transpose

// ======== Symbols ========

substitute_symbol: combine_symbol
combine_symbol: indexed_symbol | _non_indexed_symbol

single_letter_symbol: SINGLE_LETTER_SYMBOL -> combine_symbol
multi_letter_symbol: MULTI_LETTER_SYMBOL -> combine_symbol

// a formatted symbol is any symbol surrounded with a latex command which changes it visually.
// this could for example be \mathit
formatted_symbol: _cmd_format (BRACE_SURROUNDED_TEXT | SINGLE_LETTER_SYMBOL) [PRIMES]
_non_indexed_symbol: single_letter_symbol | multi_letter_symbol | formatted_symbol

indexed_symbol: _non_indexed_symbol _UNDERSCORE (single_letter_symbol | _digit | BRACE_SURROUNDED_TEXT) [PRIMES]

// all the rules here should return the NAME (as in a str) of the symbol to be created
// the symbol rule is responsible for eactually creating the symbol and optionally substituting its value.

// this rule optionally tries to create a unit, instead of a symbol, if bunits are used.
// otherwise this is the same as the symbol rule.
unit: _L_BRACE combine_symbol _R_BRACE

// ======== Numbers ========

// groups any value which evaluates to a number.
_number: _numeric_number | _digit
// groups any value which evaluates to a number, and can be passed as an argument, without surrounding it with braces.
// it may be a bit counter intuitive, but here pi (and other constants) are essentially seen as a "_digit".
_digit: _numeric_digit | _constant

_constant: CONST_INFINITY

_numeric_digit: NUMERIC_DIGIT
_numeric_number: HEXADECIMAL_NUMBER | BASE_10_NUMBER | OCTAL_NUMBER | BINARY_NUMBER

// ======== Functions ========

// matches a potential function application, anything of the form,
// f (x, y, ....)      where 'f' is some symbol.
// if 'f' turns out to *not* be a symbol, this should just be interpreted as an implicit
// multiplication between 'f' and the singular argument in its parameter list.
// If there is more than one argument in its parameter list, a syntax error should be
// raised
maybe_function_application: combine_symbol (_L_PAREN list_of_expressions _R_PAREN | _L_BRACE _L_PAREN list_of_expressions _R_PAREN _R_BRACE)


// groups all functions which cannot be used as an argument to other functions.
// to pass this type of function, delimit them so they are matched by the _delimited_factor rule.
?function_noarg: _postfix_function

// groups all functions which can be used as arguments to other functions without needing to be delimited.
?function_as_arg: _delimited_function
    | named_function
    | _series_function
    | integral
    | sqrt
    | conjugate
    | frac
    | binom
    | _derivative
    | _postfix_function_arg

?named_function: maybe_function_application
    | trig_function
    | _log
    | exponential
    | limit
    | real_part | imaginary_part | argument | sign
    | upper_gamma | lower_gamma
    | _filter_functions
    | _matrix_functions
    | _combinatorial_functions
    | _divisibility_functions

// matches a special kind of argument, defined by the fact that fractions and binomials can be passed without surrounding them with braces.
substitute_single_letter_symbol.1: single_letter_symbol -> substitute_symbol
?function_special_arg: braces_expression | frac | binom | substitute_single_letter_symbol | _digit


// named functions

_func_template{func_name}: func_name [_CARET function_special_arg] factor_func_arg

// trigonometric functions

trig_function: _func_template{FUNC_SIN}
    | _func_template{FUNC_COS}
    | _func_template{FUNC_TAN}
    | _func_template{FUNC_CSC}
    | _func_template{FUNC_SEC}
    | _func_template{FUNC_COT}
    | _func_template{FUNC_ASIN}
    | _func_template{FUNC_ACOS}
    | _func_template{FUNC_ATAN}
    | _func_template{FUNC_ACSC}
    | _func_template{FUNC_ASEC}
    | _func_template{FUNC_ACOT}
    | _func_template{FUNC_SINH}
    | _func_template{FUNC_COSH}
    | _func_template{FUNC_CSCH}
    | _func_template{FUNC_SECH}
    | _func_template{FUNC_COTH}
    | _func_template{FUNC_TANH}
    | _func_template{FUNC_ASINH}
    | _func_template{FUNC_ACOSH}
    | _func_template{FUNC_ATANH}
    | _func_template{FUNC_ACSCH}
    | _func_template{FUNC_ASECH}
    | _func_template{FUNC_ACOTH}

_log: log_implicit_base
    | log_explicit_base

log_implicit_base: _func_template{FUNC_LOG}
    | _func_template{FUNC_LN}
    | _func_template{FUNC_LG}

log_explicit_base: FUNC_LOG _UNDERSCORE function_special_arg [_CARET function_special_arg] factor_func_arg
    | FUNC_LOG _CARET function_special_arg _UNDERSCORE function_special_arg factor_func_arg -> log_explicit_base_exponent_first

real_part: _func_template{_FUNC_RE}
imaginary_part: _func_template{_FUNC_IM}
argument: _func_template{_FUNC_ARG}
sign: _func_template{_FUNC_SGN}

exponential: _func_template{_FUNC_EXP}


upper_gamma: _FUNC_UPPER_GAMMA expression (_COMMA expression)? _R_PAREN
lower_gamma: _FUNC_LOWER_GAMMA expression _COMMA expression _R_PAREN


limit_direction: _L_BRACE (ADD|SUB) _R_BRACE
    | ADD
    | SUB

limit: _FUNC_LIMIT _UNDERSCORE _L_BRACE substitute_symbol _RIGHT_ARROW basefactor_arg [_CARET limit_direction] _R_BRACE factor_func_arg

// prioritize delimited expressions over terms, such that e.g. \sum_{j = 0}^5 (j) j is parsed as Sum(j, (j, 0, 5)) * j and not Sum(j ** 2, (j, 0, 5)).
_delimited_arg.1: _delimitedfactor
_delimited_arg_or_term: _delimited_arg | term

_series_template_start_iter_first{series_name}: series_name _UNDERSCORE _L_BRACE substitute_symbol EQUAL expression _R_BRACE _CARET function_special_arg _delimited_arg_or_term
_series_template_end_iter_first{series_name}: series_name _CARET function_special_arg _UNDERSCORE _L_BRACE substitute_symbol EQUAL expression _R_BRACE _delimited_arg_or_term

_series_function: sum | product

sum: _series_template_start_iter_first{_FUNC_SUM} -> sum_start_iter_first
    | _series_template_end_iter_first{_FUNC_SUM} -> sum_end_iter_first


product: _series_template_start_iter_first{_FUNC_PRODUCT} -> product_start_iter_first
    | _series_template_end_iter_first{_FUNC_PRODUCT} -> product_end_iter_first
    
// filter functions

_filter_functions: min | max

list_of_expressions: expression (_COMMA expression)*

min: _FUNC_MIN _L_PAREN list_of_expressions _R_PAREN
max: _FUNC_MAX _L_PAREN list_of_expressions _R_PAREN

// delimited functions
_delimited_function: abs | norm | inner_product | floor | ceil

%declare _INNER_PRODUCT_SEPARATOR
inner_product: _L_ANGLE expression _INNER_PRODUCT_SEPARATOR expression _R_ANGLE
abs: _L_BAR expression _R_BAR
norm: _L_DOUBLE_BAR expression _R_DOUBLE_BAR
floor: _L_FLOOR expression _R_FLOOR
ceil: _L_CEIL expression _R_CEIL
sqrt: _FUNC_SQRT [brackets_expression] (braces_expression|substitute_single_letter_symbol|_digit)
conjugate: _FUNC_CONJUGATE (braces_expression|substitute_single_letter_symbol|_digit)

// match a single argument in a list of latex style arguments (that is \command{arg1}{arg2}...{argN})
_multiarg_func_arg: (braces_expression|substitute_single_letter_symbol|_digit)
// terminals signifying the delimiters and end of multiple arguments in a latex style argument list.
// due to lalr's limited lookahead, a custom post lexer needs to insert this token when parsing.
%declare _MULTIARG_DELIMITER
%declare _MULTIARG_EOS

// postfix functions

_postfix_function: factorial | percent | permille | derivative_prime | modulo

// postfix functions can generally not be passed as an argument to other mathematical functions,
// e.g. \sin(x)!, where (x)! would be the postfix function call.
// if this was allowed, then \sin(x)! would be interpreted as \sin((x)!), but from a human reader perspective,
// this is unexpected, and interpreting it as (\sin(x))! is more natural.
//
// Omitting these parenthesees changes this perception though,
// as e.g. \sin x! is more likely to be interpreted as \sin((x)!)
//
// Therefore, some postfix functions may have an additional rule, postfixed with _func_arg,
// which matches all cases of the postfix function such that it can be passed as an argument to another function.
//
// all of these rules are grouped together in _postfix_function_arg
_postfix_function_arg: factorial_func_arg | percent_func_arg | permille_func_arg | derivative_prime_func_arg

factorial: _delimitedfactor _BANG
factorial_func_arg: factor_func_postfix_arg _BANG -> factorial

percent: factor_func_arg _PERCENT
percent_func_arg: factor_func_postfix_arg _PERCENT -> percent
permille: factor_func_arg _PERMILLE
permille_func_arg: factor_func_postfix_arg _PERMILLE -> permille
derivative_prime: factor_func_arg PRIMES
derivative_prime_func_arg: factor_func_postfix_arg PRIMES -> derivative_prime

modulo: factor_func_arg _FUNC_MOD factor_func_arg

// core functions
// TODO: just add 2 more terminals, which match cases where arguments are not delimited,
// there are a limited number of cases where this is allowed, so it should be doable?
frac: _FUNC_FRAC _multiarg_func_arg _MULTIARG_DELIMITER _multiarg_func_arg _MULTIARG_EOS
binom: _FUNC_BINOM _multiarg_func_arg _MULTIARG_DELIMITER _multiarg_func_arg _MULTIARG_EOS

diff_symbol_exponent: combine_symbol [_CARET function_special_arg]
diff_symbol_arg_list: ((_DIFFERENTIAL_SYMBOL|_PARTIAL_SYMBOL) diff_symbol_exponent)+

// _L_BRACE_R_BRACE_PAIR.1: _R_BRACE _WS? _L_BRACE

_derivative: derivative_func_first | derivative_symbols_first | derivative_phys_symbols_first | derivative_phys_func_first

derivative_func_first: (_FUNC_DERIVATIVE [_L_BRACKET expression _R_BRACKET]|_FUNC_PARTIAL_DERIVATIVE [_CARET function_special_arg]) expression _R_BRACE _L_BRACE diff_symbol_arg_list _R_BRACE
derivative_symbols_first: (_FUNC_DERIVATIVE [_L_BRACKET expression _R_BRACKET]|_FUNC_PARTIAL_DERIVATIVE [_CARET function_special_arg]) _R_BRACE _L_BRACE diff_symbol_arg_list _R_BRACE _delimited_arg_or_term
derivative_phys_func_first: _FUNC_PHYS_DERIVATIVE [ _L_BRACKET expression _R_BRACKET ] _L_BRACE expression _R_BRACE _L_BRACE combine_symbol _R_BRACE
derivative_phys_symbols_first: _FUNC_PHYS_DERIVATIVE [ _L_BRACKET expression _R_BRACKET ] _L_BRACE combine_symbol _R_BRACE _delimited_arg_or_term

integral: _FUNC_INTEGRAL [expression] (_DIFFERENTIAL_SYMBOL|_PARTIAL_SYMBOL) combine_symbol -> integral_no_bounds
    | _FUNC_INTEGRAL _UNDERSCORE function_special_arg _CARET function_special_arg [expression] (_DIFFERENTIAL_SYMBOL|_PARTIAL_SYMBOL) combine_symbol -> integral_lower_bound_first
    | _FUNC_INTEGRAL _CARET function_special_arg _UNDERSCORE function_special_arg [expression] (_DIFFERENTIAL_SYMBOL|_PARTIAL_SYMBOL) combine_symbol -> integral_upper_bound_first

// ======== Matrices ========

// det_matrix is differentiated from the other matrices, as this one evaluates to the determinant value, which is a scalar and not a matrix.
// TODO: different name for these?
_matrix_notation: _matrix_type | det_matrix
_matrix_type: matrix | array_matrix

matrix_row_delim: MATRIX_ROW_DELIM -> matrix_like_delim
matrix_body: matrix_row_delim? expression ((_MATRIX_COL_DELIM|matrix_row_delim) expression)* matrix_row_delim?
matrix: CMD_BEGIN_MATRIX matrix_body CMD_END_MATRIX _MATRIX_ENV_END
array_matrix: CMD_BEGIN_ARRAY ARRAY_ENV_OPTIONS matrix_body CMD_END_ARRAY _MATRIX_ENV_END
det_matrix: CMD_BEGIN_VMATRIX matrix_body CMD_END_VMATRIX _MATRIX_ENV_END

// ======== Matrices functions ========

_matrix_functions: determinant | trace | adjugate | rref | unitvec | gradient | hessian | jacobian | taylor

determinant: _func_template{_FUNC_MATRIX_DETERMINANT}
trace: _func_template{_FUNC_MATRIX_TRACE}
adjugate: _func_template{_FUNC_MATRIX_ADJUGATE}
rref: _func_template{_FUNC_MATRIX_RREF}
unitvec: _func_template{_FUNC_VEC_UNIT}

gradient: _func_template{_FUNC_GRADIENT}
hessian: _func_template{_FUNC_HESSIAN}
jacobian: _func_template{_FUNC_JACOBIAN}

taylor: _FUNC_TAYLOR _UNDERSCORE _L_BRACE expression _COMMA expression [_COMMA expression] _R_BRACE _L_PAREN expression (_COMMA expression)* _R_PAREN

// ======== Combinatorial functions ========

_combinatorial_functions: permutations | combinations | derangements

permutations: _FUNC_PERMUTATIONS expression _COMMA expression _R_PAREN
combinations: _FUNC_COMBINATIONS expression _COMMA expression _R_PAREN
derangements: _FUNC_DERANGEMENTS expression _R_PAREN
    | _L_BRACE _BANG expression _R_BRACE

// ======== Divisibility functions ========

_divisibility_functions: gcd | lcm 

gcd: _FUNC_GCD _L_PAREN expression _COMMA expression _R_PAREN
lcm: _FUNC_LCM _L_PAREN expression _COMMA expression _R_PAREN

// ======== System of relations ========

// there are two ways to denote a system of relations.
// 1) in some latex environment (align or cases currently)
// 2) separating the relations with a logical and operator

%declare _SOR_EXPR_DELIM

// environment SOR (system of relatiosn) rules

sor_env_delim: _SOR_EXPR_DELIM -> matrix_like_delim
_sor_env_body: sor_env_delim?  relation (sor_env_delim relation)* sor_env_delim?
sor_env: _CMD_BEGIN_ALIGN _sor_env_body _CMD_END_ALIGN
    | _CMD_BEGIN_CASES _sor_env_body _CMD_END_CASES

// land SOR rules

sor_and_chain: relation (_PROP_OP_AND relation)*

_system_of_relations: sor_env | sor_and_chain

// ================ Terminals ================

// ignore escaped whitespace in latex code

_WS: /[\s\t\n\r]+/

_TEXT: CMD_TEXT _WS? BRACE_SURROUNDED_TEXT
// any tokens appearing in ANY terminals which are not ignored, should all be individually ignored and NOT be part of this,
// as it will otherwise be prioritized incorrectly.
_IGNORE.-1: /(?<!\\)\\ /
    | "\\," | "\\thinspace" | "\\:" | "\\medspace" | "\\;" | "\\thickspace"
    | "\\quad" | "\\qquad"
    | "\\!" | "\\negthinspace" | "\\negmedspace" | "\\negthickspace"   
    | "\\vrule" | "\\vcenter" | "\\vbox" | "\\vskip" | "\\vspace" | "\\hfill"
    | "\\*" | "\\-" | "\\." | "\\/" | "\\(" | "\\=" | "\\middle"
    | "\\limits" | "\\nolimits"
    | "~"
    | "\\displaystyle"
    | _TEXT

_L_FORMAT: "\\left"
_R_FORMAT: "\\right"

%ignore _WS
%ignore _R_FORMAT
%ignore _L_FORMAT
%ignore _IGNORE

// basic binary operators
ADD: "+"
SUB: "-"
MUL: "*"
DIV: "/" | "\\over"

// basic common operators
_CMD_TIMES: "\\times"
_CMD_XPROD: /\\cross(product)?/ | "\\cp"
_CMD_CDOT:  "\\cdot"
_CMD_VDOT: "\\dotproduct" | "\\vdot"
_CMD_DIV:   "\\div"
_CMD_BAR: "\\bar"
_CMD_OVERLINE: "\\overline"
_CMD_INNER_PRODUCT_SEPARATOR: _BAR | _COMMA

// tokens with distinct left and right symbols
_L_ANGLE: "\\langle" | "<"
_R_ANGLE: "\\rangle" | ">"
_L_BRACE: "{"
_R_BRACE: "}"
L_BRACE_LITERAL: "\\{"
R_BRACE_LITERAL: "\\}"
_L_BRACKET: "["
_R_BRACKET: "]"
_L_CEIL: "\\lceil"
_R_CEIL: "\\rceil"
_L_FLOOR: "\\lfloor"
_R_FLOOR: "\\rfloor"
_L_PAREN: "("
_R_PAREN: ")"
_L_BAR: _BAR
%declare _R_BAR
_L_DOUBLE_BAR: _DOUBLE_BAR
%declare _R_DOUBLE_BAR

_L_DELIMITER: _DOT | _L_ANGLE | L_BRACE_LITERAL | _L_BRACKET | _L_CEIL | _L_FLOOR | _L_PAREN
_R_DELIMITER: _DOT | _R_ANGLE | R_BRACE_LITERAL | _R_BRACKET | _R_CEIL | _R_FLOOR | _R_PAREN


// This terminal matches any piece of text surrounded with {...}, IF its contents contain balanced braces.
// Due to lalr's limited 1 lookahead, this needs to be a single terminal with a rather conveluted regex,
// Below is a breakdown of it:
//
//  (                   :
//    {                 : Initial left brace
//    (?:               : 
//      [^{}]+          : Match any text up till '{' or '}'
//      |               : OR
//      (?-1)           : recursively match the entire regex
//    )*                : Do this as much as needed 
//    }                 : Final right brace
//  )                   :
//
// NOTE: this does not currently support escaped braces, it just treats them as they were unescaped.
BRACE_SURROUNDED_TEXT: /({(?:[^{}]+|(?-1))*})/ 


// limit, integral, sum, and product symbols
_FUNC_LIMIT:  /\\lim(?!its)/
_FUNC_INTEGRAL:  "\\int" | "\\intop"
_FUNC_SUM:  "\\sum"
_FUNC_PRODUCT: "\\prod"
_RIGHT_ARROW: /\\(?:to|(?:long)?rightarrow)/


// common functions
_FUNC_EXP:  "\\exp"
FUNC_LOG:  "\\log"
FUNC_LN:   "\\ln"
FUNC_LG:   "\\lg"
_FUNC_MIN: "\\min"
_FUNC_MAX: "\\max"
_FUNC_CONJUGATE: _CMD_OVERLINE | _CMD_BAR
_FUNC_RE.1: "\\Re" | "\\real" | CMD_OPERATOR _WS? _L_BRACE _WS? "Re" _WS? _R_BRACE
_FUNC_IM.1: "\\Im" | "\\imaginary" | CMD_OPERATOR _WS? _L_BRACE _WS? "Im" _WS? _R_BRACE
_FUNC_ARG: "\\arg"
_FUNC_SGN.1: CMD_OPERATOR _WS? _L_BRACE _WS? "sgn" _WS? _R_BRACE

// multiarg functions

_FUNC_FRAC: /\\[dtcs]?frac/ | "\\nicefrac"
_FUNC_BINOM: /\\[dt]?binom/

_FUNC_DERIVATIVE: _FUNC_FRAC _WS? _L_BRACE _WS? _DIFFERENTIAL_SYMBOL
_FUNC_PARTIAL_DERIVATIVE: _FUNC_FRAC _WS? _L_BRACE _WS? _PARTIAL_SYMBOL

_FUNC_PHYS_DERIVATIVE: /\\(?:p(?:artial)?)?derivative/ | /\\p?dv\*?/

_FUNC_OVERLINE: "\\overline"

// trigonometric functions
FUNC_SIN:  "\\sin"
FUNC_COS:  "\\cos"
FUNC_TAN:  "\\tan"
FUNC_CSC:  "\\csc"
FUNC_SEC:  "\\sec"
FUNC_COT:  "\\cot"

// inverse trigonometric functions
FUNC_ASIN: "\\arcsin"
FUNC_ACOS: "\\arccos"
FUNC_ATAN: "\\arctan"
FUNC_ACSC: "\\arccsc"
FUNC_ASEC: "\\arcsec"
FUNC_ACOT: "\\arccot"

// hyperbolic trigonometric functions
FUNC_SINH: "\\sinh"
FUNC_COSH: "\\cosh"
FUNC_TANH: "\\tanh"
FUNC_CSCH: "\\csch"
FUNC_SECH: "\\sech"
FUNC_COTH: "\\coth"
FUNC_ASINH: CMD_OPERATOR _WS? _L_BRACE _WS? "arsinh" _WS? _R_BRACE
FUNC_ACOSH: CMD_OPERATOR _WS? _L_BRACE _WS? "arcosh" _WS? _R_BRACE
FUNC_ATANH: CMD_OPERATOR _WS? _L_BRACE _WS? "artanh" _WS? _R_BRACE
FUNC_ACSCH: CMD_OPERATOR _WS? _L_BRACE _WS? "arcsch" _WS? _R_BRACE
FUNC_ASECH: CMD_OPERATOR _WS? _L_BRACE _WS? "arsech" _WS? _R_BRACE
FUNC_ACOTH: CMD_OPERATOR _WS? _L_BRACE _WS? "arcoth" _WS? _R_BRACE

_FUNC_SQRT: "\\sqrt"
_FUNC_UPPER_GAMMA.1: "\\Gamma" _L_FORMAT? _L_PAREN
_FUNC_LOWER_GAMMA.1: "\\gamma" _L_FORMAT? _L_PAREN

// matrix functions

_FUNC_MATRIX_DETERMINANT: "\\det"
_FUNC_MATRIX_TRACE: /\\[Tt]r(ace)?/
_FUNC_MATRIX_ADJUGATE: CMD_OPERATOR _WS? _L_BRACE _WS? "adjugate" _WS? _R_BRACE
_FUNC_MATRIX_RREF: CMD_OPERATOR _WS? _L_BRACE _WS? "rref" _WS? _R_BRACE
// this needs to have priority, so \vectorunit is not parsed as the symbol \vec{torunit}
_FUNC_VEC_UNIT:  /\\v(ectorunit|u)\*?/

// linear alg functions.

_FUNC_GRADIENT.1: "\\nabla" | /\\grad(ient)?/
_FUNC_HESSIAN.1: CMD_MATRIX_FORMAT _WS? _L_BRACE _WS? "H" _WS? _R_BRACE
_FUNC_JACOBIAN.1: CMD_MATRIX_FORMAT _WS? _L_BRACE _WS? "J" _WS? _R_BRACE

// Match any "T" which has at least 1 comma in its index string and is followed by parenthesees.
// The lookahead "(?=...)" ensures we do not match the index string itself,
// as the transformer needs these as individual tokens.
//
// Technically this means some indexed "T" symbols may rarely be incorrectly matched to this terminal,
// e.g. "T_{x_{1,1}}(y)" would be matched by this, but these scenarios are very obscure anyways, so it should not be an issue.
//
_FUNC_TAYLOR.1: /T(?=\s*_\s*{([^,]+?,)+.+?}(\\left)?\(.+?\))/s // (\\right)? check is not needed as .+ accounts for this

// combinatorial functions.

// all combinatorial functions should have to be called with their arguments wrapped in parenthesees,
// therefore they are defined a bit differently here.

_CMD_PERMUTATIONS: "P"
_CMD_COMBINATIONS: "C"
_CMD_DERANGEMENTS: "D"

_FUNC_PERMUTATIONS.1: _CMD_PERMUTATIONS _L_FORMAT? _L_PAREN
_FUNC_COMBINATIONS.1: _CMD_COMBINATIONS _L_FORMAT? _L_PAREN
_FUNC_DERANGEMENTS.1: _CMD_DERANGEMENTS _L_FORMAT? _L_PAREN

// divisibility functions.

_FUNC_GCD: "\\gcd"
_FUNC_LCM: CMD_OPERATOR _WS? _L_BRACE _WS? "lcm" _WS? _R_BRACE
_FUNC_MOD: "\\mod"

// TODO: use a bit more elaborate regex here, so more complex strings are allowed in the index.
// UNDEFINED_FUNC_START: (SINGLE_LETTER_SYMBOL|MULTI_LETTER_SYMBOL) (_WS? _UNDERSCORE _WS? _L_BRACE /\s*[^{}]+\s*/ _R_BRACE)? _LR_FORMAT? _L_PAREN

// un-redefinable mathematical constants
CONST_INFINITY: "\\infty"

// Text formatting

CMD_MATH: /\\math\w+/
//         do not match \vec followed by tor, as many formatters starting with vector... would be matched by this instead.
//                         do not match \var as \va{r}, as this means none of the \var... greek letters are usable.
CMD_VEC: /\\vec(?!tor)/ | /\\va(?:\*|(?!r))/ | "\\vectorarrow"
CMD_VECBOLD: "\\vectorbold" |/\\vb\*?/
CMD_HAT: "\\hat"
CMD_BOLD_FORMAT: "\\pmb"

_cmd_format: CMD_MATH | CMD_VEC | CMD_VECBOLD | CMD_HAT | CMD_BOLD_FORMAT | DELTA_UPPER
CMD_TEXT: /\\text(bf|it|sf|tt|sc|normal|up)?/ | /\\textcolor\s*{\s*\w+\s*}/



// mathrm is also included here so operatorname does not have to be used everywhere.
CMD_OPERATOR.1: "\\operatorname" | "\\mathrm"
CMD_MATRIX_FORMAT: "\\mathbf"

_BANG: "!"
_BAR: "|" | "\\mid"
_DOUBLE_BAR: "||" | /\\mid\s*\\mid/ | /\\[lr]?Vert/
_DOT: "."
_CARET: "^"
_COMMA: ","
_UNDERSCORE: "_"
_PERCENT: "\\%"
_PERMILLE: "\\textperthousand"

// relational symbols
EQUAL: "="
NOT_EQUAL: "\\neq" | /\\ne(?!g)/ // do not match \neg as '\ne' followed by the symbol 'g'
LT: "<"
LTE: LT EQUAL | "\\leq" | "\\leqslant" | /\\le(?!ft)/ // do not match `\left` as `\le` followed by the symbol `ft`
GT: ">"
GTE: GT EQUAL | "\\geq" | "\\ge" | "\\geqslant"

OPERATOR_DIV: _CMD_DIV | DIV
OPERATOR_CROSS: _CMD_TIMES | _CMD_XPROD
OPERATOR_MUL: MUL | _CMD_VDOT | _CMD_CDOT

%import .greek_symbols.GREEK_SYMBOL
%import .greek_symbols.DELTA_UPPER

_DIFFERENTIAL_SYMBOL: "\\differential" | "\\dd"
_PARTIAL_SYMBOL: "\\partial"

LATIN_SYMBOL: /[a-zA-Z]/
LATIN_SYMBOL_WITH_PRIMTES: LATIN_SYMBOL PRIMES
MULTI_LETTER_LATIN_SYMBOL: /[a-zA-Z]{2,}'*/
GREEK_SYMBOL_WITH_PRIMES: GREEK_SYMBOL PRIMES

SINGLE_LETTER_SYMBOL: LATIN_SYMBOL | GREEK_SYMBOL

MULTI_LETTER_SYMBOL: LATIN_SYMBOL_WITH_PRIMTES | GREEK_SYMBOL_WITH_PRIMES | MULTI_LETTER_LATIN_SYMBOL

%import common.DIGIT -> NUMERIC_DIGIT

BINARY_NUMBER: /0(b|\\mathrm{b})[01]+/ | /\\mathrm{0b[01]+}/

OCTAL_NUMBER: /0(o|\\mathrm{o})[0-7]+/ | /\\mathrm{0o[0-7]+}/

HEXADECIMAL_NUMBER: /0[xX][\da-fA-F]+/ | /\\mathrm{0[xX][\da-fA-F]+}/

BASE_10_NUMBER: NUMERIC_DIGIT NUMERIC_DIGIT+ | NUMERIC_DIGIT* _DOT NUMERIC_DIGIT+

PRIMES: "'"+

ADJOINT_TRANSPOSE_EXPONENT: /(\\prime|\\ast|'|\*)/
ADJOINT_TRANSPOSE_EXPONENTS: /{(\\prime|\\ast|'|\*|\s)+}/

CMD_BEGIN: "\\begin" _WS? _L_BRACE
CMD_END: "\\end" _WS? _L_BRACE

// matrices

ARRAY_ENV: "array"
MATRIX_ENV: /([bp]?(?:small)?)matrix/
VMATRIX_ENV: /v(small)?matrix/

%declare _MATRIX_ENV_END

CMD_BEGIN_MATRIX: CMD_BEGIN _WS? MATRIX_ENV _WS? _R_BRACE
CMD_END_MATRIX: CMD_END _WS? MATRIX_ENV _WS? _R_BRACE

CMD_BEGIN_VMATRIX: CMD_BEGIN _WS? VMATRIX_ENV _WS? _R_BRACE
CMD_END_VMATRIX: CMD_END _WS? VMATRIX_ENV _WS? _R_BRACE

CMD_BEGIN_ARRAY: (_L_FORMAT _WS? _L_DELIMITER)? _WS? CMD_BEGIN _WS? ARRAY_ENV _WS? _R_BRACE
ARRAY_ENV_OPTIONS: _L_BRACE (/[clr|:\s]+/)? _R_BRACE
CMD_END_ARRAY: CMD_END _WS? ARRAY_ENV _WS? _R_BRACE _WS? (_R_FORMAT _WS? _R_DELIMITER)?

%declare _MATRIX_COL_DELIM
%declare MATRIX_ROW_DELIM

_ALIGN: "&"
_LATEX_NEWLINE: "\\\\"

// system of relations
_CMD_BEGIN_ALIGN: CMD_BEGIN _WS? "align" _WS? _R_BRACE
_CMD_BEGIN_CASES: CMD_BEGIN _WS? "cases" _WS? _R_BRACE
_CMD_END_ALIGN: CMD_END _WS? "align" _WS? _R_BRACE
_CMD_END_CASES: CMD_END _WS? "cases" _WS? _R_BRACE

_PROP_OP_AND: /\\(big)?wedge/
    | "\\land"