%import .cas_expr._IGNORE -> _CAS_EXPR__IGNORE
%import .cas_expr (_L_FORMAT, _R_FORMAT, _WS, ADD, SUB, LT, LTE, GT, GTE, _L_BRACE, _R_BRACE, _L_PAREN, _R_PAREN, _CMD_OVERLINE, _CMD_BAR, _UNDERSCORE, _COMMA, _PROP_OP_AND)
// should these be aliased? it does not really make a difference, but i guess it makes sense to do it?
%import .cas_expr._symbol -> _cas_expr__symbol
%import .cas_expr.undefined_function -> cas_expr__undefined_function
%import .cas_expr.relation
%import .cas_logic_expr.cas_logic_expression

// what is the left hand side?
// - symbol
// - symbol + function arg list
// i think that is it?

// what is the right hand side?
// - relation
// - set? (for assumptions)

// what is the separator
// - := (definition)
// - \stackrel{def}{=}
// - \stackrel{\mathrm{def}}{=}
// - \vcentcoloneq(q?)
// - =: (for flipping stuff?)
// - \in (assumptions)
// - \mapsto (undefined function assumptions)

// what is a definition expression?
// let def_expr represent a singular definition rule, then multiple def_expr are added via. the following methods.
//
// whitespace command: <--- And all of this stuff last [ ]
// def_expr \quad def_expr (x := 5 \quad y := 10)
//
// chained with logical and
// def_expr \land def_expr (x := 5 \land y := 10)
//
// system of expressions environments:
// \begin{cases}
// x &:= 5 \\
// y &:= 10 \\
// \end{cases}


// some definitions examples:
// == DEFINING A VARIABLE ==  <--- Start Here [ ]
// x := 5
// f (x, y) := x^2
// ^ ^
// | |
// Symbol
//   |
//   Function Arguments
// 
// == DEFINING ASSUMPTIONS ON A SYMBOL == <--- Then Here [ ]
//
// x \in R (assume x to be Real)
// x, y, z \in \mathbbm{Z} (assume x, y and z to be integers).
//
// == DEFINE SYMBOL TO BE AN UNDEFINED FUNCTION == <--- And Finally Here [ ]
// f (x, y, z) \mapsto \mathbbm{R} (the symbol 'f', should be interpreted as a function taking 3 arguments, x, y and z, and its output always being a part of the real numbers set)
//

cas_logic_expr_def: symbol_cas_logic_expr_def (_DEF_SPACE symbol_cas_logic_expr_def)* -> cas_expr_def

cas_expr_def: _definition ((_PROP_OP_AND|_DEF_SPACE) _definition)*

_definition: symbol_cas_expr_def | function_def | assumption_def | function_assumption_def

symbol_cas_logic_expr_def: symbol _DEF_OP cas_logic_expression -> symbol_cas_expr_def

symbol_cas_expr_def: symbol _DEF_OP [relation]

function_def: symbol function_params _DEF_OP [relation]

assumption_def: symbol (_COMMA symbol)* _VAR_ASSUME_OP _assumption_set

function_assumption_def: symbol function_params _FUN_ASSUME_OP _assumption_set

function_params: _L_PAREN symbol (_COMMA symbol)* _R_PAREN

?symbol: _cas_expr__symbol

_assumption_set: _signed_set
    | SET_COMPLEX
    | SET_IMAGINARY
    | algebraic_set
    | positive_set
    | nonnegative_set
    | negative_set
    | nonpositive_set
    | natural0_set

_signed_set: SET_REAL|ext_real_set|SET_RATIONAL|SET_INTEGER|SET_EVEN|SET_ODD|SET_PRIME 
ext_real_set: (_CMD_OVERLINE|_CMD_BAR) _L_BRACE? SET_REAL _R_BRACE?
algebraic_set: (_CMD_OVERLINE|_CMD_BAR) _L_BRACE? SET_RATIONAL _R_BRACE?
positive_set: _signed_set _UNDERSCORE (_L_BRACE? ADD _R_BRACE?| _L_BRACE GT "0" _R_BRACE)
nonnegative_set: _signed_set _UNDERSCORE _L_BRACE GTE "0" _R_BRACE
negative_set: _signed_set _UNDERSCORE (_L_BRACE? SUB _R_BRACE?| _L_BRACE LT "0" _R_BRACE)
nonpositive_set: _signed_set _UNDERSCORE _L_BRACE LTE "0" _R_BRACE
natural0_set: SET_NATURAL _UNDERSCORE _L_BRACE? "0" _R_BRACE?

// ======== TERMINALS ========

%ignore _CAS_EXPR__IGNORE
%ignore _WS
%ignore _L_FORMAT
%ignore _R_FORMAT

_DEF_SPACE.1: /\\q?quad/ | "\\enspace"

_DEF_OP: ":=" | /\\vcentcolonqq?/ | "\\stackrel{def}{=}" | "\\stackrel{\\mathrm{def}}{=}" | "\\triangleq"
// use this when declaring assumptions on a variable
_VAR_ASSUME_OP: /\\in(?!t)/
// use this when declaring assumptions on a function.
_FUN_ASSUME_OP: /\\(long)?mapsto/

// sets for assumptions
_SET_FORMATTER: /\\(pmb|boldsymbol|mathbf|mathbbm?|mathcal|mathscr)/
_CMD_SET_MINUS: "\\setminus" | "\\backslash" | "-"
_CMD_SET: "\\set"

SET_COMPLEX: _SET_FORMATTER _WS? _L_BRACE _WS? "C" _WS? _R_BRACE | "C"
SET_REAL: _SET_FORMATTER _WS? _L_BRACE _WS? "R" _WS? _R_BRACE | "R"
SET_IMAGINARY: _SET_FORMATTER _WS? _L_BRACE _WS? "I" _WS? _R_BRACE | "I"
SET_RATIONAL: _SET_FORMATTER _WS? _L_BRACE _WS? "Q" _WS? _R_BRACE | "Q"
SET_INTEGER: _SET_FORMATTER _WS? _L_BRACE _WS? "Z" _WS? _R_BRACE | "Z"
SET_NATURAL: _SET_FORMATTER _WS? _L_BRACE _WS? "N" _WS? _R_BRACE | "N"
SET_EVEN: _SET_FORMATTER _WS? _L_BRACE _WS? "E" _WS? _R_BRACE | "E"
SET_ODD: _SET_FORMATTER _WS? _L_BRACE _WS? "O" _WS? _R_BRACE | "O"
SET_PRIME: _SET_FORMATTER _WS? _L_BRACE _WS? "P" _WS? _R_BRACE | "P"
