#!/bin/bash
set -e
echo Activating Virtual Env

if [ "$(uname -s | grep -i 'mingw\|msys\|cygwin')" ]; then
    BIN_DIR="Scripts"
else
    BIN_DIR="bin"
fi

source .venv/${BIN_DIR}/activate

echo Running Tests

pytest -x
npm run test

echo Code Quality Checks

ruff check --preview
npx eslint ./src

echo Pre Push Completed
