name: Push Changes To Repo

on:
  push:
    branches:
      - "*"

permissions:
  contents: write

jobs:
  run-tests:
    uses: ./.github/workflows/test.yml
  tmp-docs:
    uses: ./.github/workflows/docs.yml
