name: Push Changes To Repo

on:
  push:
    branches:
      - "*"

  pull_request:
    branches:
      - "*"
jobs:
  run-tests:
    uses: ./.github/workflows/test.yml
  run-code-quality-checks:
    uses: ./.github/workflows/code-quality.yml
