name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"
    branches:
      - "*"

  pull_request:
    branches:
      - main
env:
  PLUGIN_NAME: obsidian-obsimat-plugin

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          git clone https://github.com/sympy/sympy.git
          pip install -e sympy

      - name: Run tests
        run: |
          pytest --ignore=sympy


  sympy-client-build:
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install Pip Dependencies
        id: install-pip-dependencies
        run: |
          python -m venv .venv
          .venv/scripts/activate
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Build Executable
        id: build-executable
        run: | 
          .venv/scripts/activate
          pyinstaller --onefile --collect-data sympy --path=".venv/Lib/site-packages" --add-data "./sympy-client/src/grammar/obsimat_grammar.lark:grammar" sympy-client/src/SympyClient.py

      - name: Upload SympyClient Executable
        uses: actions/upload-artifact@v4
        with:
          name: SympyClient
          path: ./dist/SympyClient.exe

  plugin-build:
    runs-on: ubuntu-latest
    needs: [ test, sympy-client-build ]
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Build Plugin
        run: |
          npm install
          npm run build
      
      - name: Download SympyClient Executable
        uses: actions/download-artifact@v4
        with:
          name: SympyClient
          path: bin
        
      - name: Create Plugin Zip
        run: |
          mkdir ${{ env.PLUGIN_NAME }}
          cp main.js manifest.json styles.css bin/SympyClient.exe ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }} ${{ env.PLUGIN_NAME }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.PLUGIN_NAME }}.zip
          asset_name: ${{ env.PLUGIN_NAME }}-${{ github.ref_name }}.zip
          asset_content_type: application/zip

      