name: Test Cas Client

on:
  - workflow_call

jobs:
  test-sympy-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Run tests
        run: |
          pytest
  
  test-result:
    runs-on: ubuntu-latest
    if: always()
    needs: [ test-sympy-client ]
    steps:
      - name: Failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: | 
          echo "Test failed!"
          exit 1
  