name: Test Cas Client

on:
  - workflow_call

jobs:
  test-cas-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Run tests
        run: |
          pytest
  
  test-plugin:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Npm Install
        run: npm ci
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Setup CAS Virtual Environment
        shell: bash
        run: |
          python -m venv .venv
          source .venv/bin/activate || . .venv/Scripts/activate
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
      - name: Run Tests
        run: npm run test

  test-result:
    runs-on: ubuntu-latest
    if: always()
    needs: [ test-cas-client, test-plugin ]
    steps:
      - name: Failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: | 
          echo "Test failed!"
          exit 1
  